"""empty message

Revision ID: 03b9b4b5070c
Revises: 
Create Date: 2020-05-20 14:12:12.160958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b9b4b5070c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('src', sa.String(length=255), nullable=False),
    sa.Column('dst', sa.String(length=255), nullable=False),
    sa.Column('app', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accesses')
    # ### end Alembic commands ###
